module.exports = {
  consumer_key:'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',  
  consumer_secret:'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  access_token_key:'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',  
  access_token_secret:'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx'
}